### PR TITLE
compiled program stops when no link is present in a passage

### PR DESCRIPTION
**Pull request by bompf**

### CODE REVIEW

**Comment by bompf** [comment]
Should work now. Please review, @TweeZcodeCompiler/owners.

**Comment by bompf** [comment]
Your twee doc contained an error (`landoftheiguanas` had a preceding space character). I added some error handling to make this error less confusing.

**Comment by Potregon** [comment]
Its compiles fine, but I expected that the following code display the english links instead of the german passage names.
```
::Start
[[One|Eins]]
::Eins
End
```
Was that changed in this pull request?

**Comment by bompf** [comment]
No. I need static strings for that.

**Comment by bompf** [comment]
The `TaleOfTheIguanaSimpleLinks.twee` example causes an error on frotz an gargoyle, during the second iteration of the main loop in the routine in `display_links`. If you output the assembly and place the following lines:

```
   print "foo1"
   passage_not_set:
   print "foo2"
   add i 1 -> i
   jl i PASSAGES_COUNT ?loop_start
```

Output becomes:

```
foo21: landoftheiguanas
foo1foo2foo2foo2foo22: Fatal error: Illegal opcode
[Hit any key to exit.]
```

It seems like the jump is not performed correctly.

**Pull request merged**
